In [1]:
import pandas as pd
import numpy as np

from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import NearestNeighbors
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
import matplotlib.lines as mlines

In [2]:
df = pd.read_csv('CNAE-9.data', header = None)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1080 entries, 0 to 1079
Columns: 857 entries, 0 to 856
dtypes: int64(857)
memory usage: 7.1 MB

In [4]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,847,848,849,850,851,852,853,854,855,856
count,1080.000000,1080.000000,1080.000000,1080.000000,1080.000000,1080.000000,1080.000000,1080.000000,1080.000000,1080.000000,...,1080.000000,1080.000000,1080.000000,1080.000000,1080.000000,1080.000000,1080.000000,1080.000000,1080.000000,1080.000000
mean,5.000000,0.002778,0.000926,0.000926,0.000926,0.000926,0.001852,0.036111,0.000926,0.001852,...,0.000926,0.000926,0.001852,0.005556,0.058333,0.002778,0.000926,0.000926,0.025000,0.002778
std,2.583185,0.052656,0.030429,0.030429,0.030429,0.030429,0.043013,0.210017,0.030429,0.043013,...,0.030429,0.030429,0.043013,0.074363,0.234481,0.052656,0.030429,0.030429,0.173085,0.052656
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,9.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000

In [5]:
y = df.pop(0).values

In [6]:
# from sklearn.preprocessing import MinMaxScaler
# df_n = df.copy()
# df_n.loc[:, :] = MinMaxScaler().fit_transform(df)
# df_n.describe()

In [7]:
from sklearn.preprocessing import Normalizer
df_n = df.copy()
df_n.iloc[:,:] = Normalizer(norm='l2').fit_transform(df)
df_n.describe()

,1,2,3,4,5,6,7,8,9,10,...,847,848,849,850,851,852,853,854,855,856
count,1080.000000,1080.000000,1080.000000,1080.000000,1080.000000,1080.000000,1080.000000,1080.000000,1080.000000,1080.000000,...,1080.000000,1080.000000,1080.000000,1080.000000,1080.000000,1080.000000,1080.000000,1080.000000,1080.000000,1080.000000
mean,0.000939,0.000293,0.000327,0.000350,0.000279,0.000625,0.011193,0.000126,0.000616,0.000535,...,0.000293,0.000309,0.000707,0.002035,0.018768,0.000765,0.000279,0.000126,0.007856,0.000815
std,0.018505,0.009623,0.010758,0.011501,0.009175,0.014842,0.064054,0.004141,0.015136,0.017568,...,0.009623,0.010143,0.016659,0.028230,0.076808,0.016014,0.009175,0.004141,0.055023,0.016538
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,0.447214,0.316228,0.353553,0.377964,0.301511,0.408248,0.612372,0.136083,0.447214,0.577350,...,0.316228,0.333333,0.447214,0.500000,0.447214,0.447214,0.301511,0.136083,0.666667,0.447214

In [15]:
NN_e = KNeighborsClassifier(metric = 'euclidean')
NN_c = KNeighborsClassifier(metric = 'cosine')
NN_m = KNeighborsClassifier(metric = 'manhattan')
NN_mink = KNeighborsClassifier(p=5)

In [16]:
X = df.values
print("Not normalized \n")

scores = cross_val_score(NN_e, X, y, cv=10)
print("4x CV (Euclidean Distance):")
print(scores)
print(scores.mean())

scores = cross_val_score(NN_c, X, y, cv=10)
print("\n4x CV (Cosine):") 
print(scores)
print(scores.mean())

scores = cross_val_score(NN_m, X, y, cv=10)
print("\n4x CV (Manh):") 
print(scores)
print(scores.mean())


scores = cross_val_score(NN_mink, X, y, cv=10)
print("\n4x CV (Mink):") 
print(scores)
print(scores.mean())

Not normalized

4x CV (Euclidean Distance):
[0.85185185 0.87037037 0.86111111 0.88888889 0.85185185 0.85185185
 0.85185185 0.84259259 0.87037037 0.87037037]
0.861111111111111

4x CV (Cosine):
[0.90740741 0.90740741 0.92592593 0.93518519 0.90740741 0.93518519
 0.90740741 0.87962963 0.91666667 0.96296296]
0.9185185185185185

4x CV (Manh):
[0.87037037 0.93518519 0.88888889 0.90740741 0.86111111 0.84259259
 0.85185185 0.81481481 0.85185185 0.88888889]
0.8712962962962963

4x CV (Mink):
[0.80555556 0.85185185 0.87962963 0.87962963 0.87962963 0.84259259
 0.84259259 0.84259259 0.86111111 0.88888889]
0.8574074074074074

In [17]:
X = df_n.values
print("Normalized\n")

scores = cross_val_score(NN_e, X, y, cv=10)
print("4x CV (Euclidean Distance):")
print(scores)
print(scores.mean())

scores = cross_val_score(NN_c, X, y, cv=10)
print("\n4x CV (Cosine):") 
print(scores)
print(scores.mean())

scores = cross_val_score(NN_m, X, y, cv=10)
print("\n4x CV (Manh):") 
print(scores)
print(scores.mean())

scores = cross_val_score(NN_mink, X, y, cv=10)
print("\n4x CV (Mink):") 
print(scores)
print(scores.mean())

Normalized

4x CV (Euclidean Distance):
[0.88888889 0.93518519 0.88888889 0.93518519 0.88888889 0.92592593
 0.89814815 0.88888889 0.90740741 0.96296296]
0.9120370370370372

4x CV (Cosine):
[0.89814815 0.90740741 0.92592593 0.94444444 0.88888889 0.93518519
 0.89814815 0.87037037 0.91666667 0.96296296]
0.9148148148148149

4x CV (Manh):
[0.86111111 0.85185185 0.87037037 0.93518519 0.87037037 0.87037037
 0.86111111 0.87037037 0.86111111 0.87962963]
0.8731481481481481

4x CV (Mink):
[0.82407407 0.87037037 0.91666667 0.88888889 0.89814815 0.86111111
 0.87037037 0.90740741 0.89814815 0.91666667]
0.8851851851851851